[patch.crates-io]
candle-core = { path="libs/candle/candle-core" }

[workspace]
members = ["crates/rwkv", "crates/rusty_bar", "crates/chess", "crates/rwkv_test"]
exclude = ["libs/*", "libs/candle/candle-core/"]

[workspace.dependencies]
burn = {git="https://github.com/tracel-ai/burn", default-features=false }
burn-import = {git="https://github.com/tracel-ai/burn", default-features=false, features=["pytorch"] }
rwkv-tokenizer = {path="libs/rwkv-tokenizer/rwkv-tokenizer"}
