[package]
name = "rwkv_rl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
tracing-subscriber = "0.3.19"
serde_json = "1.0.138"

burn = {version="0.16.0", default-features=false }
#burn-hip = {git="https://github.com/tracel-ai/burn", optional=true, default-features=false }
#cubecl-hip-sys = { version = "6.3.1001", optional=true, default-features=false, features=["rocm__6_2_4"] }
llama-burn = { path = "libs/models/llama-burn", package = "llama-burn", features = ["llama3", "pretrained"], default-features=false }
tokenizers = "0.21.0"
burn-import = "0.16.0"

[features]
wgpu = ["burn/wgpu"]
#hip = ["burn/hip"]
cuda = ["burn/cuda-jit"]
candle = ["burn/candle"]
#vulkan = ["burn/vulkan"]
fusion = ["burn/fusion"]
ndarray = ["burn/ndarray", "burn/openblas", "burn/openblas-system"]