[package]
name = "rwkv_rl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
tracing-subscriber = "0.3.19"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }

#burn = {version="0.16.0", default-features=false }
#burn-import = {version="0.16.0", default-features=false, features=["pytorch"] }
burn = {git="https://github.com/tracel-ai/burn", default-features=false }
burn-import = {git="https://github.com/tracel-ai/burn", default-features=false, features=["pytorch"] }

#burn-hip = {git="https://github.com/tracel-ai/burn", optional=true, default-features=false }
#cubecl-hip-sys = { version = "6.3.1001", optional=true, default-features=false, features=["rocm__6_2_4"] }
#llama-burn = { path = "libs/models/llama-burn", package = "llama-burn", default-features=false }
rwkv = {path="crates/rwkv"}
rwkv-tokenizer = {path="libs/rwkv-tokenizer/rwkv-tokenizer"}


[workspace]
members = ["crates/rwkv", "crates/rusty_bar", "crates/chess"]

[features]
wgpu = ["burn/wgpu"]
#hip = ["burn/hip"]
cuda = ["burn/cuda"]
#candle = ["burn/candle"]
vulkan = ["burn/vulkan"]
fusion = ["burn/fusion"]
#ndarray = ["burn/ndarray", "burn/openblas"]
